service:
  name: whereis-lambda

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getLocationInfo:
    handler: handler.getLocationInfo
    events:
      - http:
          method: get
          path: getLocationInfo
