name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn
      
    - name: Build
      run: yarn build-app
      
    - name: Copy files
      run: |
        mkdir -p public
        cp -r packages/whereis-app/build/* public
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.4.6
      with:
        BRANCH: gh-pages
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAN: true
